### ISSUE TITLE
Missing index.js for the client?

### ISSUE THREAD

**Issue by 101arg101** [endel/LD35#2]
Is there supposed to be an index.js file in the client directory? The package.json says there is.

**Comment by endel** [comment]
Hey @101arg101, 

Sorry, this game was made in a gamejam 🙈  the `index` property in the `package.json` doesn't reflect reality. 

The entrypoint is actually defined on [`webpack.config.js`](https://github.com/endel/LD35/blob/master/client/webpack.config.js#L8)

**Comment by 101arg101** [comment]
Thanks, got it working now. Never worked with webpack until now.
